"use strict";

const translations = { en: { eyebrow:"W.B. GLOBAL DEFENSE // SECURE CHANNEL", subtitle:"OPERATION // NO DARK", start:"START", settings:"SETTINGS", credits:"CREDITS", exit:"EXIT", offline:"OFFLINE BUILD", language:"LANGUAGE", audio:"AUDIO", back:"BACK", partnershipLabel:"PARTNERSHIP", authorLabel:"AUTHOR", creatorLabel:"CREATOR", author:"O Escritor", classification:"CLASSIFIED // MISSION BRIEFING", operationTitle:"OPERATION: NO DARK", agentLabel:"AGENT:", department:"GLOBAL DEFENSE DEPARTMENT / CIA", radioInteraction:"RADIO INTERACTION", secureChannel:"SECURE CHANNEL", radioMessage:"— Buck, recover the files and proceed to the extraction point.", continue:"CONTINUE" }, pt: { eyebrow:"DEFESA GLOBAL W.B. // CANAL SEGURO", subtitle:"OPERAÇÃO // NO DARK", start:"INICIAR", settings:"CONFIGURAÇÕES", credits:"CRÉDITOS", exit:"SAIR", offline:"VERSÃO OFFLINE", language:"IDIOMA", audio:"ÁUDIO", back:"VOLTAR", partnershipLabel:"PARCERIA", authorLabel:"AUTOR", creatorLabel:"CRIADOR", author:"O Escritor", classification:"CLASSIFICADO // BRIEFING DA MISSÃO", operationTitle:"OPERAÇÃO: NO DARK", agentLabel:"AGENTE:", department:"DEPARTAMENTO DE DEFESA GLOBAL / CIA", radioInteraction:"INTERAÇÃO DE RÁDIO", secureChannel:"CANAL SEGURO", radioMessage:"— Buck, recupere os arquivos e vá para o ponto de extração.", continue:"CONTINUAR" } };
const state = { language: localStorage.getItem("tdj-language") || "en", audio: localStorage.getItem("tdj-audio") !== "off" };
const $ = (selector) => document.querySelector(selector); const $$ = (selector) => [...document.querySelectorAll(selector)]; const text = (key) => translations[state.language][key] || translations.en[key] || key;
function applyLanguage() { document.documentElement.lang = state.language === "pt" ? "pt-BR" : "en"; $$('[data-i18n]').forEach((node) => { node.textContent = text(node.dataset.i18n); }); $$('[data-language]').forEach((button) => button.classList.toggle("active", button.dataset.language === state.language)); updateAudio(); }
function updateAudio() { const toggle = $("#audio-toggle"); if (!toggle) return; toggle.classList.toggle("off", !state.audio); toggle.setAttribute("aria-pressed", String(state.audio)); $("#audio-state").textContent = state.audio ? "ON" : "OFF"; }
function openModal(id) { $(`#${id}-modal`)?.classList.remove("hidden"); } function closeModal(id) { $(`#${id}-modal`)?.classList.add("hidden"); }
function showMission() { $("#main-menu").classList.add("hidden"); $("#mission-screen").classList.remove("hidden"); }
function showScene() { $("#mission-screen").classList.add("hidden"); $("#scene-screen").classList.remove("hidden"); TDJMission.init(); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("visible"); setTimeout(() => toast.classList.remove("visible"), 2600); }

document.addEventListener("click", (event) => { const button = event.target.closest("[data-action]"); if (!button) return; const action = button.dataset.action; if (action === "start") showMission(); if (action === "mission-continue") showScene(); if (action === "mission-back") { $("#mission-screen").classList.add("hidden"); $("#main-menu").classList.remove("hidden"); } if (action === "settings") openModal("settings"); if (action === "credits") openModal("credits"); if (action === "exit") showToast("EXIT // OFFLINE BUILD"); });
document.addEventListener("click", (event) => { const close = event.target.closest("[data-close]"); if (close) closeModal(close.dataset.close); const language = event.target.closest("[data-language]"); if (language) { state.language = language.dataset.language; localStorage.setItem("tdj-language", state.language); applyLanguage(); } });
$("#audio-toggle")?.addEventListener("click", () => { state.audio = !state.audio; localStorage.setItem("tdj-audio", state.audio ? "on" : "off"); updateAudio(); });
window.addEventListener("keydown", (event) => { if (event.key !== "Escape") return; $$(".modal:not(.hidden)").forEach((modal) => modal.classList.add("hidden")); if (!$("#scene-screen").classList.contains("hidden")) { $("#scene-screen").classList.add("hidden"); $("#mission-screen").classList.remove("hidden"); } else if (!$("#mission-screen").classList.contains("hidden")) { $("#mission-screen").classList.add("hidden"); $("#main-menu").classList.remove("hidden"); } });
applyLanguage();
